server:
  port: 9000
spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:./db_batch;Mode=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  batch:
    jdbc:
      initialize-schema: always
logging:
  level:
    com.example.practicesbb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE